apiVersion: v1
kind: Service
metadata:
  name: todo-service-staging
spec:
  selector:
    app: todo
  type: LoadBalancer
  ports:
    - name: tcp
      protocol: TCP
      port: 31000  # External Port
      targetPort: 3000  # Target Port