apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-app-staging
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: denishjackson/todo-test:v0.1.0
    argocd-image-updater.argoproj.io/write-back-method: git
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/denishjackson1/devtest.git
    targetRevision: main # branch to track
    path: environments/staging/app
  destination:
    server: https://kubernetes.default.svc 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
