apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrary
resources:
  - deployment.yaml
  - namespace.yaml
  - service.yaml
  - postgres-service.yaml
  - postgres-deployment.yaml
  - secret.yaml
  - volume-claim.yaml
  - volume.yaml