apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    name: production
    environment: production
spec:
  capacity:
    storage: 500Mi
  storageClassName: standard
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/denish/pv/production"